In [1]:
#NOTE: Trained on the filtered CGM data

from Glucose_processor import GlucoseDataProcessor
from models.model_A import BloodGlucosePredictorA
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [2]:
Glucose_data = GlucoseDataProcessor(CGM_file_path="CGM_data.csv", bolus_file_path="Bolus_data.csv", carb_file_path="Carb_data.csv",
                                    min_range=69, max_range=180, target=85, tp=75, td=280, dp=45, dd=180)


df = Glucose_data.create_filtered_DataFrame()

# Initialize the predictor
horizons = [5, 10, 15, 20, 30, 60]
predictor = BloodGlucosePredictorA(horizons)

# Preprocess data (including handling missing values with interpolation)
X, y = predictor.preprocess_data(df)

df

d:\DiaPulse\models\model_A.py:21: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='linear', inplace=True)  # Linear interpolation for missing values


Time         CGM  Insulin Activity  Food Activity  hour  \
3255 2024-12-09 01:57:16   74.633941          0.000000       0.000000     1   
3254 2024-12-09 02:02:16   77.013161          0.000000       0.000000     2   
3253 2024-12-09 02:07:16   79.895722          0.000000       0.000000     2   
3252 2024-12-09 02:12:16   83.361943          0.000000       0.000000     2   
3251 2024-12-09 02:17:16   87.477852          0.000000       0.000000     2   
...                  ...         ...               ...            ...   ...   
16   2024-12-20 12:51:29  109.909232          0.027243       0.137798    12   
15   2024-12-20 12:56:28  112.474523          0.029130       0.145712    12   
14   2024-12-20 13:01:28  115.372253          0.030675       0.151448    13   
13   2024-12-20 13:06:27  118.539996          0.031900       0.155199    13   
12   2024-12-20 13:11:27  121.911326          0.032843       0.157202    13   

      minute  second  hour_fraction  hour_sin  hour_cos      BG_t+5  \
3255      57      16       0.081435  0.489636  0.871927   77.013161   
3254       2      16       0.084907  0.508541  0.861038   79.895722   
3253       7      16       0.088380  0.527203  0.849739   83.361943   
3252      12      16       0.091852  0.545615  0.838036   87.477852   
3251      17      16       0.095324  0.563766  0.825934   92.286805   
...      ...     ...            ...       ...       ...         ...   
16        51      29       0.535752 -0.222754 -0.974875  112.474523   
15        56      28       0.539213 -0.243897 -0.969801  115.372253   
14         1      28       0.542685 -0.264995 -0.964250  118.539996   
13         6      27       0.546146 -0.285897 -0.958260  121.911326   
12        11      27       0.549618 -0.306734 -0.951795  125.417160   

         BG_t+10     BG_t+15     BG_t+20     BG_t+30     BG_t+60  
3255   79.895722   83.361943   87.477852   97.802204  141.931251  
3254   83.361943   87.477852   92.286805  104.002860  149.747136  
3253   87.477852   92.286805   97.802204  110.830518  157.142641  
3252   92.286805   97.802204  104.002860  118.188673  163.892997  
3251   97.802204  104.002860  110.830518  125.942857  169.790115  
...          ...         ...         ...         ...         ...  
16    115.372253  118.539996  121.911326  128.991958  149.673834  
15    118.539996  121.911326  125.417160  132.581176  152.754635  
14    121.911326  125.417160  128.991958  136.144884  155.653519  
13    125.417160  128.991958  132.581176  139.656314  158.336854  
12    128.991958  132.581176  136.144884  143.096135  160.773267  

[3244 rows x 16 columns]

In [3]:
X

array([[0.74482366, 0.93597281, 0.12469817, 0.        , 0.        ],
       [0.75427609, 0.93052827, 0.13181539, 0.        , 0.        ],
       [0.76360751, 0.92487882, 0.14043831, 0.        , 0.        ],
       ...,
       [0.36749975, 0.01786527, 0.24656313, 0.49885655, 0.54377471],
       [0.35704839, 0.02086009, 0.25603914, 0.51878209, 0.557242  ],
       [0.34663001, 0.02409258, 0.26612417, 0.5341104 , 0.56443417]])

In [4]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(np.shape(X_train))

(2595, 5)


In [5]:
# Build and train the model
predictor.build_model(input_shape=(1, X_train.shape[1]))
predictor.train(X_train, y_train, epochs=200)

# Evaluate the model
loss, mae = predictor.evaluate(X_test, y_test)
print(f'Test Loss: {loss:.4f}, Test MAE: {mae:.4f}')

# Make predictions
predictions = predictor.predict(X_test)
print(f"Predicted: {predictions[0]}, Actual: {y_test[0]}")

d:\DiaPulse\venv\lib\site-packages\keras\src\layers\rnn\rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/200
65/65 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.1194 - mae: 0.2932 - val_loss: 0.0316 - val_mae: 0.1280
Epoch 2/200
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0264 - mae: 0.1225 - val_loss: 0.0202 - val_mae: 0.1055
Epoch 3/200
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0191 - mae: 0.1035 - val_loss: 0.0140 - val_mae: 0.0889
Epoch 4/200
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0130 - mae: 0.0859 - val_loss: 0.0086 - val_mae: 0.0693
Epoch 5/200
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0076 - mae: 0.0643 - val_loss: 0.0056 - val_mae: 0.0528
Epoch 6/200
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0051 - mae: 0.0510 - val_loss: 0.0047 - val_mae: 0.0456
Epoch 7/200
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0044 - mae: 0.0449 - val_loss: 0.0044 - val_mae: 0.0429
Epoch 8/200
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0043 - mae: 0.0430 - val_loss: 0.0043 - val_mae: 0.0421
Epoch 9/200
65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.004

In [6]:
# Make predictions
predictions = predictor.predict(X_test)
print(f"Predicted: {predictions}, Actual: {predictor.scaler_y.inverse_transform(y_test)}")

import plotly.express as px
p=[]
for i in predictions:
    p.append(i[0])

act=[]
for i in predictor.scaler_y.inverse_transform(y_test):
    act.append(i[0])
# Plot the predictions
fig = px.scatter(x=act, y=p)
fig.show()

21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
Predicted: [[116.499054 116.933205 117.91314  118.580444 120.69563  125.40613 ]
 [140.51619  140.03415  139.50958  139.4608   139.40643  139.12614 ]
 [124.22723  122.01225  120.489105 120.5385   119.11738  119.02689 ]
 ...
 [281.46085  281.681    281.98495  280.58582  280.97406  267.1514  ]
 [147.88463  146.94463  146.03156  144.8643   142.47282  134.5745  ]
 [119.09115  120.583496 120.80595  122.5909   125.73376  138.84415 ]], Actual: [[115.68099018 116.11647811 116.43210122 116.6360243  116.75265081
  115.6457738 ]
 [141.90096235 143.96009482 145.31242341 145.93436273 145.04036859
  131.21688567]
 [120.04030854 115.26705186 110.60472831 106.05829888  97.36183889
   76.08331765]
 ...
 [279.44750953 278.99487317 278.43474277 277.78022599 276.24344591
  269.35088175]
 [147.31933049 146.81246292 146.33045252 145.82746848 144.61012603
  137.9299182 ]
 [114.34248679 110.46610889 106.50859019 102.540643    94.78172624
   74.08035774]]


In [7]:
# Look at the fit on the training data
predictions = predictor.predict(X_train)
print(f"Predicted: {predictions}, Actual: {predictor.scaler_y.inverse_transform(y_train)}")

import plotly.express as px
p=[]
for i in predictions:
    p.append(i[-2])

act=[]
for i in predictor.scaler_y.inverse_transform(y_train):
    act.append(i[-2])
# Plot the predictions
fig = px.scatter(x=act, y=p)
fig.show()

82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
Predicted: [[123.78579  122.5973   121.97856  122.234474 122.46375  128.14226 ]
 [205.64726  203.92665  202.61707  201.8661   198.66698  184.26973 ]
 [132.65773  130.62839  128.8204   128.31459  125.04065  112.980156]
 ...
 [ 87.77069   87.97452   87.702126  88.74988   91.436806 104.2004  ]
 [114.50515  115.32862  116.89659  117.87716  121.1253   128.69057 ]
 [120.335945 119.255    118.624084 117.8515   116.494835 113.246895]], Actual: [[116.97685441 110.87062994 105.17530672  99.93232707  90.90653936
   76.68645267]
 [200.34126483 195.2741952  190.28796458 185.40903146 176.01475281
  150.2538493 ]
 [131.63562655 129.45047851 126.87068886 123.93452154 117.15100085
   92.35599475]
 ...
 [ 83.95172316  80.56180879  77.26991762  74.08035774  68.10060601
   56.22999194]
 [116.45368173 120.88836532 125.71149708 130.88337925 142.02493417
  174.26926702]
 [121.62647405 122.64335844 123.82532479 125.12317967 127.87648413
  133.88764085]]
